#include <iostream>
#include <stdio.h>
#include <algorithm>
#include <vector>
#include <set>
#include <malloc.h>
#include <stdlib.h>
#include <list>
#include <queue>
#include <math.h>
#include <string>
#include <string.h>
#include <cstring>
